name: Tag Releases

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Github Tag Bump and `latest` tag update
      uses: WiktorJ/github-tag-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
